# Generated by Django 6.0.7 on 2026-08-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Pokemon',
        ),
    ]
